### PR TITLE
Adds Warden::GitHub's new verified serializer

### PR DESCRIPTION
**Pull request by rauhryan**

### CODE REVIEW

**Comment by rauhryan** [comment]
howdy @fphilipe 

Not sure why the travis tests didn't pass, all the tests pass locally

Thanks

**Comment by fphilipe** [comment]
Not sure why the tests failed. Could you explain to me what this does exactly and why it's needed? Thanks :blush:

**Comment by ippeiukai** [comment]
@fphilipe 
I believe this is a step towards fixing https://github.com/fphilipe/warden-github-rails/issues/10. At least I was searching for a way to setup `Warden::GitHub::Verifier` in order to solve it.
Note atmos/warden-github@bd1596a indicates that `WARDEN_GITHUB_VERIFIER_SECRET` needs be set in order for this to work. Also, I suspect this change invalidates existing sessions.

@rauhryan 
The tests are failing for Rails 3.1 although passing for 3.2 and 4.0. Maybe the serializer didn't work before 3.2?

**Comment by fphilipe** [comment]
@rauhryan I'm not sure it makes sense to add this since rails encrypts the cookies anyways. See https://github.com/atmos/warden-github/pull/43#issuecomment-142509155. What do you think?

**Comment by fphilipe** [comment]
@rauhryan Sorry to not have looked closer into this PR. I was fixing the issue and dug deeper and now fully understand the issue at hand, which led me to write a fix for this in #19. Might want to try that out if you want.

**Pull request closed without merging**
